###
GET http://localhost:3000/api/employees HTTP/1.1

###
GET http://localhost:3000/api/employees/4 HTTP/1.1

###
POST http://localhost:3000/api/employees HTTP/1.1
Content-Type: application/json

{
    "name": "Francis Favia 88",
    "salary": 33
}

###
PATCH http://localhost:3000/api/employees/9 HTTP/1.1
Content-Type: application/json

{
    "name": "New Alessandro Peralta XDXDXD",
    "salary": 1323
}

###
DELETE http://localhost:3000/api/employees/9 HTTP/1.1